### ISSUE TITLE
Issue with line.split

### ISSUE THREAD

**Issue by Sidu28** [threelittlemonkeys/rnn-encoder-decoder-pytorch#1]
I don't think the way the line.split was inplemented in the prepare.py is correct.  Is there a sample data set that you have that works?

**Comment by threelittlemonkeys** [comment]
There are some in the machine-translation folder. You can try:
`~/github/rnn-encoder-decoder-pytorch/machine-translation$ python3 ../prepare.py sample.enfr`

**Comment by Sidu28** [comment]
Ok, so does file type matter?  Could I use a txt or rtf file with the same exact formatting (one tab between the sequences?

Because when I copy an paste those samples into a simple text file (rtf on mac), I get the following error:

ValueError: not enough values to unpack (expected 2, got 1)

**Comment by threelittlemonkeys** [comment]
Would you specify on which line the error occurs?

**Comment by Sidu28** [comment]
Sorry, here it is:
Traceback (most recent call last):
  File "prepare.py", line 38, in <module>
    data, x_cti, x_wti, y_wti = load_data()
  File "prepare.py", line 10, in load_data
    x, y = line.split("\t")
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by Sidu28** [comment]
This is what I copied into my rtf file:

You got my breasts, didn't you?	Mes seins ne suffisent pas?
Then the first shock came.	Une main me glissait un caoutchouc entre les dents, puis la première décharge.
Oh God.	Oh mon Dieu.
Random stops.	Faites des contrôles aléatoires.

**Comment by threelittlemonkeys** [comment]
Oh you have to use a plain text file, not rtf. If you want to use rtf, you need to convert it to txt first.

**Comment by Sidu28** [comment]
Ok, thank you.  I was able to prepare the data in a file called training.txt
When I go to train, I input the following:
"python train.py model vocab.src vocab.tgt training.txt num_epoch"
\But I get the error:

Usage: train.py model vocab.src.char_to_idx vocab.src.word_to_idx vocab.tgt.word_to_idx training_data num_epoch

Are all these different parameters included in the repository?

**Comment by threelittlemonkeys** [comment]
When you run `python3 prepare.py training.txt`, you get those index files. Then you can run, for example: `python3 train.py model training.txt.src.char_to_idx training.txt.src.word_to_idx training.txt.tgt.char_to_idx training.txt.tgt.word_to_idx training.txt.csv 10`. All the other hyperpaparmeters are set in `parameters.py`.

**Comment by Sidu28** [comment]
is there any way to get the encoded output tensor of the RNN?  Where would I go in train.py to get that vector?

**Comment by threelittlemonkeys** [comment]
Forward pass is done on line 44 in `train.py`:
```
loss = model(xc, xw, y0) # forward pass and compute loss
```
This calls the `rnn_encoder_decoder.forward()` function in `model.py`, and on lines 18, 19:
```
self.dec.hs = self.enc(b, xc, xw, lens)
self.dec.hidden = self.enc.hidden
```
`self.enc(b, xc, xw, lens)` is the output tensor of the encoder, and `self.enc.hidden` is its hidden state.

**Comment by Sidu28** [comment]
Is there anyway to extract the output tensor as a numpy array? Because I can't decode what the formatting of the output is
